module.exports = `APP_NAME=%__MODEL_NAME__%
APP_ENV=local
APP_MODE=single
APP_KEY=%__APP_KEY__%
APP_DEBUG=true
APP_URL=http://localhost
APP_PORT=8000
APP_SOCKET_PORT=8008

API_PREFIX=/api

DB_CONNECTION=mongo
DB_HOST=localhost
DB_PORT=27017
DB_DATABASE=test_db
DB_USERNAME=null
DB_PASSWORD=null

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=mailhog
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="%__MODEL_NAME__%"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
`
