module.exports = (options) => `{
  "name": "${options.name}",
  "version": "${options.version}",
  "description": "${options.description}",
  "main": "app.js",
  "repository": "${options.repository}",
  "author": "${options.author}",
  "license": "${options.license}",
  "private": ${options.private},
  "scripts": {
    "install:ui": "yarn --cwd ./resource/node-mvc-ui install",
    "dev": "concurrently \"yarn dev:server\" \"yarn dev:ui\"",
    "dev:ui": "yarn --cwd ./resource/node-mvc-ui serve",
    "dev:server": "nodemon app.js --ignore 'docs/*.*'",
    "start:ui": "yarn --cwd ./resource/node-mvc-ui build && yarn --cwd ./resource/node-mvc-ui start --mode production",
    "start": "pm2 start ecosystem.config.js",
    "restart": "pm2 restart ecosystem.config.js",
    "stop": "pm2 stop ecosystem.config.js",
    "make:env": "node ./core/Console/cmd/env",
    "make:entity": "node ./core/Console/cmd/entity",
    "make:model": "node ./core/Console/cmd/model",
    "make:controller": "node ./core/Console/cmd/controller",
    "make:router": "node ./core/Console/cmd/routesGroup",
    "make:service": "node ./core/Console/cmd/service",
    "make:middleware": "node ./core/Console/cmd/middleware",
    "make:migration": "node ./core/Console/cmd/migrate",
    "make:test": "jest",
    "init:test": "jest --init",
    "delete:entity": "node ./core/Console/cmd/delete/entity",
    "delete:model": "node ./core/Console/cmd/delete/model",
    "delete:controller": "node ./core/Console/cmd/delete/controller",
    "delete:service": "node ./core/Console/cmd/delete/service",
    "delete:middleware": "node ./core/Console/cmd/delete/middleware",
    "create:owner": "node ./core/Console/cmd/owners",
    "create:admin": "node ./core/Console/cmd/admins",
    "reset:admin:password": "node ./core/Console/cmd/adminsPasswordReset",
    "reset:owner:password": "node ./core/Console/cmd/ownersPasswordReset",
    "gen:docs": "node ./core/Console/cmd/docs"
  },
  "dependencies": {
    "axios": "^0.21.1",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.19.0",
    "chalk": "^4.1.0",
    "clear": "^0.1.0",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "fs-promise": "^2.0.3",
    "helmet": "^4.3.1",
    "helmet-csp": "^3.3.1",
    "jsonwebtoken": "^8.5.1",
    "mongoose": "^5.11.11",
    "mongoose-autopopulate": "^0.12.3",
    "mongoose-paginate-v2": "^1.3.13",
    "morgan": "^1.10.0",
    "multer": "^1.4.2",
    "pg": "^8.5.1",
    "pluralize": "^8.0.0",
    "pm2": "^4.5.1",
    "redis": "^3.0.2",
    "socket.io": "^3.1.0",
    "uuid": "^8.3.2",
    "vhost": "^3.0.2"
  },
  "devDependencies": {
    "concurrently": "^5.3.0",
    "jest": "^26.6.3",
    "jest-extended": "^0.11.5",
    "nodemon": "^2.0.7"
  }
}
`;
